run_name: csa_mnid_bps
seed: 17
output_root: runs
mnid:
  input_dir: datasets/Beethoven_motif-main/csv_notes_clean
  bps_fh_dir: datasets/BPS_FH_Dataset
  dict_file: MNID/data_creation/prepare_data/dict/CP.pkl
  ckpt_dir: MNID/BPS_MNID_MI
  cpu: false
motif:
  method: CSA
  csv_label_dir: datasets/Beethoven_motif-main/csv_label
  motif_midi_dir: datasets/Beethoven_motif-main/motif_midi
  save_predictions: true
